### ISSUE TITLE
LangChain task list

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#134]
- [ ] Make URL getting work
- [ ] Can ground report more by showing matching words as well as matching n-grams from actual sources
- [ ] Add ability to do new separate chat and go back to other chats
- [ ] Add ability to download chat(s).
- [ ] Consume url from chat itself and do look up
- [ ] https://github.com/h2oai/makersaurus
- [ ] Make All just mean look at all dbs
- [ ] Allow any github link to ingest if not on HF.      If on HF, default to h2oGPT and DAI docs.
- [ ] Unsure how to work around https://github.com/chroma-core/chroma/issues/412#issuecomment-1547027011
- [ ] Good or Bad for Flag, and Compare should be which is better

**Comment by G-force78** [comment]
Was just about to post that I am not able to select the individual document in the UI, I see you have it on your list to implement. I hackily deleted tmp files under gradio as it kept answering about a machine learning idea and it did answer from the uploaded txt file (im using a collab notebook).

Which interaction method is best to query uploaded documents? prompt-answer, summarise etc?

**Comment by pseudotensor** [comment]
Hi @G-force78 , yes you can select only an individual document.  Just click x near the drop-down icon so All becomes unselected, then select any number of documents, search by name, etc.  Can be 1 document too.

As for what to put in the chat  as prompt, whatever you like!  Probably best is question/answer for a human.

**Comment by G-force78** [comment]
> Hi @G-force78 , yes you can select only an individual document. Just click x near the drop-down icon so All becomes unselected, then select any number of documents, search by name, etc. Can be 1 document too.
> 
> As for what to put in the chat as prompt, whatever you like! Probably best is question/answer for a human.

Sorry I meant what 'prompt type'? There are quite a few.

**Comment by pseudotensor** [comment]
The vector search is very literal right now.  If you ask "Summarize this document" that query won't match anything useful in the document selected.

So for now you should ask things like "What is the "named title" paper about? etc.  Something semi-literal has to match in query and document for now.
